---
name: Add a GCP Folder
description: Create a request for a new GCP Folder
title: Request a New GCP Folder
labels: [Create Folder]

body:
  - type: textarea
    id: folder-to-be-created
    attributes:
      label: What is the name of the folder to be created?
      description: Name of the folder. This must be all lowercase, begin with "hca-", include hyphens for spaces, and be no longer than 30 characters.
    validations:
      required: true
  - type: textarea
    id: folder-parent
    attributes:
      label: What is the name of this folder's parent folder?
      description: Name of the parent folder.
    validations:
      required: true
  - type: textarea
    id: describe-the-request
    attributes:
      label: Please describe the request.
      description: A clear and concise description of the requested Policy change. If a folder or project is to added or removed, please specify the name/ID of the target folder or project. If there is an update to an "allow" values list, please include the list in its entirety.
    validations:
      required: true
