---
name: Update existing GCP Org Policy
description: Create a request to update an existing GCP org policy,
  its value(s), scope, allowed values, denied values, or exclusions
title: Request GCP Org Policy Update
labels: [Update Org Policy]

body:
  - type: textarea
    id: policy-to-be-updated
    attributes:
      label: What is the name of the policy to be updated?
      description: Name of the target policy.
    validations:
      required: true
  - type: checkboxes
    id: update-type
    attributes:
      label: Please indicate below the type of policy update requested.
      description: Policy update type.
      options:
        - label: Update policy "allow" values list.
          required: false
        - label: Update policy "deny" values list.
          required: false
        - label: Add folder exclusion from policy.
          required: false
        - label: Remove folder exclusion from policy.
          required: false
        - label: Add project exclusion from policy.
          required: false
        - label: Remove project exclusion from policy.
          required: false
  - type: textarea
    id: describe-the-request
    attributes:
      label: Please describe the request.
      description: A clear and concise description of the requested Policy change. If a folder or project is to added or removed, please specify the name/ID of the target folder or project. If there is an update to an "allow" values list, please include the list in its entirety.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Please describe the expected behavior of the update.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Add any other context about the problem here.
      description: Add any other context about the problem here.
    validations:
      required: false
